In [57]:
import numpy as np

d = np.arange(start=-20, stop=30, step=5)

In [58]:
d2 = d * 10
print(d2)

[-200 -150 -100  -50    0   50  100  150  200  250]


In [59]:
print(np.add(d,d2))

[-220 -165 -110  -55    0   55  110  165  220  275]


In [60]:
d2 = d2.reshape(5,2)
print(d2)

[[-200 -150]
 [-100  -50]
 [   0   50]
 [ 100  150]
 [ 200  250]]


In [61]:
d3 = np.arange(start=1, stop=6, step =1)
print(d3)

[1 2 3 4 5]


In [65]:
d3 = d3.reshape(5,1)
d4 = d2*d3
print(d4)

[[-200 -150]
 [-200 -100]
 [   0  150]
 [ 400  600]
 [1000 1250]]


In [66]:
print(f'first row: {d4[0]}')
print(f'second row: {d4[1]}')
print(f'fifth row: {d4[4]}')
print(f'first column {d4[:,0]}')
print(f'second column {d4[:,1]}')
print(f'object id: {id(d4)}')

first row: [-200 -150]
second row: [-200 -100]
fifth row: [1000 1250]
first column [-200 -200    0  400 1000]
second column [-150 -100  150  600 1250]
object id: 4450846832


In [68]:
d4 = np.resize(d4, (2,5))
d4 = d4.flatten()
print(d4)

[-200 -150 -200 -100    0  150  400  600 1000 1250]
